export const GET_PUBLIC_PRODUCTS = 'GET_PUBLIC_PRODUCTS';
export const GET_PUBLIC_PRODUCTS_SUCCEEDED = 'GET_PUBLIC_PRODUCTS_SUCCEEDED';
export const GET_PUBLIC_PRODUCTS_FAILED = 'GET_PUBLIC_PRODUCTS_FAILED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCEEDED = 'GET_PRODUCTS_SUCCEEDED';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCEEDED = 'GET_PRODUCT_SUCCEEDED';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';

export const POST_PRODUCT = 'POST_PRODUCT';
export const POST_PRODUCT_SUCCEEDED = 'POST_PRODUCT_SUCCEEDED';
export const POST_PRODUCT_FAILED = 'POST_PRODUCT_FAILED';

export const PATCH_PRODUCT = 'PATCH_PRODUCT';
export const PATCH_PRODUCT_SUCCEEDED = 'PATCH_PRODUCT_SUCCEEDED';
export const PATCH_PRODUCT_FAILED = 'PATCH_PRODUCT_FAILED';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCEEDED = 'DELETE_PRODUCT_SUCCEEDED';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';